// This component was generated by the CLI. In order to use it in the applicationm, it must be imported by app.component.ts and then declared in @NgModule and the selector tag placed in app.component.html
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-hello-world',
  templateUrl: './hello-world.component.html',
  styleUrls: ['./hello-world.component.css']
})
export class HelloWorldComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
